name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths:
    - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'terraform/**'

  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets."ea1c6147-28bc-4e0f-a705-d85e163ecde6" }}
      ARM_CLIENT_SECRET: ${{secrets."H7F8Q~zP9rWsudfHFY_lXzWYIbruFooSEa4FcbMA"}}
      ARM_SUBSCRIPTION_ID: ${{ secrets."3bdcbea5-3621-4761-b33d-2bd0c726a06b"}}
      ARM_TENANT_ID: ${{ secrets."cf487387-ff9b-490f-95b5-8e731f147e27"}}

    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
