name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths:
    - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'terraform/**'

  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ SECRT_KEY.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{SECRT_KEY.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ SECRT_KEY.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ SECRT_KEY.AZURE_TENANT_ID }}

    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
